#!/usr/bin/env python3

"""
ALBERTA - Dynamic Pareto Acquisition
====================================

Construct an Oracle queue using a learned two-objective local-response
surrogate.

This is the final stage of the dynamic Pareto acquisition pipeline:

    fixed human calibration probe
                |
                v
    contemporary local-response measurements
                |
                v
    (H, U, H*U)
        ->
    (Delta_KL, |Delta_V|)
                |
                v
    ExtraTrees response surrogate
                |
                v
    contemporary self-play pool
                |
                v
    predicted response space
                |
                v
    exact 2D non-dominated sorting
                |
                v
    crowding-distance truncation
                |
                v
    Oracle HMI queue

Scientific objective
--------------------

The acquisition criterion does NOT directly maximize H, U, HU or
the historical scalar score I.

Instead, H/U/HU are used as predictors of measured local learner
susceptibility:

    policy susceptibility:
        Delta_KL =
            KL(pi_before || pi_after)

    value susceptibility:
        Delta_V =
            |V_after - V_before|

The Pareto selector jointly maximizes the predicted magnitudes:

    maximize
        Delta_KL_hat
        Delta_V_hat

No scalarization of the two predicted response objectives is used.

Important interpretation
------------------------

The selected positions are predicted to induce large local changes
in both actor and critic.

This is response-based acquisition.

It does NOT imply that those changes point in a beneficial learning
direction, and Delta_V is deliberately a magnitude rather than an
Oracle-value improvement.

Input requirements
------------------

The probe-response file must have been generated by the canonical:

    AL/pareto/mesure_local_response.py

The candidate self-play pool must use the corrected uncertainty
estimator that excludes untrained BC value heads.

For both probe and pool data, HU is recomputed internally as:

    HU = H * U

rather than trusted from stored JSON.

Budget
------

The annotation budget preserves the historical ALBERTA definition:

    round(BUDGET_FRACTION * raw_pool_size)

with default:

    BUDGET_FRACTION = 0.0002 = 0.02%

The denominator is intentionally the raw self-play pool size,
before duplicate / legal-position / calibration-probe filtering.

Outputs
-------

Oracle queue:

    checkpoints/queue/oracle_queue_dynamic_pareto_<epoch>.jsonl

Acquisition diagnostics:

    data/pareto/pareto_selection_<epoch>.json
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
import uuid

from datetime import datetime, timezone
from pathlib import Path

import chess.variant
import numpy as np

from scipy.stats import spearmanr

from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import (
    mean_absolute_error,
    r2_score,
)
from sklearn.model_selection import (
    KFold,
    cross_val_predict,
)


# ============================================================
# Project root
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

if str(PROJECT_ROOT) not in sys.path:

    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


# ============================================================
# Defaults
# ============================================================

DEFAULT_LEARNER_EPOCH = 14

DEFAULT_PROBE_RESPONSE_PATH = (
    PROJECT_ROOT
    / "data"
    / "pareto"
    / "pareto_local_responses.jsonl"
)

DEFAULT_PROBE_QUEUE_PATH = (
    PROJECT_ROOT
    / "checkpoints"
    / "queue"
    / "oracle_queue_1-10_pareto_probe.jsonl"
)

DEFAULT_SELFPLAY_DIR = (
    PROJECT_ROOT
    / "data"
    / "selfplay_jsons"
)

DEFAULT_QUEUE_DIR = (
    PROJECT_ROOT
    / "checkpoints"
    / "queue"
)

DEFAULT_DIAGNOSTIC_DIR = (
    PROJECT_ROOT
    / "data"
    / "pareto"
)

DEFAULT_BUDGET_FRACTION = 0.0002
DEFAULT_SEED = 42

DEFAULT_CV_FOLDS = 5
DEFAULT_N_TREES = 300
DEFAULT_PREDICT_CHUNK_SIZE = 100000

FEATURE_NAMES = (
    "H",
    "U",
    "HU",
)


# ============================================================
# CLI
# ============================================================

def parse_args() -> argparse.Namespace:

    parser = argparse.ArgumentParser(
        description=(
            "Build an ALBERTA Oracle queue using a learned "
            "two-objective local-response Pareto criterion."
        )
    )

    parser.add_argument(
        "--learner-epoch",
        type=int,
        default=DEFAULT_LEARNER_EPOCH,
        help=(
            "Learner generation associated with the current "
            "probe responses and candidate pool."
        ),
    )

    parser.add_argument(
        "--probe-responses",
        type=Path,
        default=DEFAULT_PROBE_RESPONSE_PATH,
        help=(
            "JSONL generated by mesure_local_response.py."
        ),
    )

    parser.add_argument(
        "--probe-queue",
        type=Path,
        default=DEFAULT_PROBE_QUEUE_PATH,
        help=(
            "Fixed human calibration queue. Its FENs are excluded "
            "from the candidate decision pool."
        ),
    )

    parser.add_argument(
        "--pool",
        type=Path,
        default=None,
        help=(
            "Current corrected self-play uncertainty JSON. "
            "If omitted, "
            "data/selfplay_jsons/"
            "uncertainty_stats_pareto_oracle_<epoch>.json "
            "is used."
        ),
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output Oracle queue. If omitted, "
            "checkpoints/queue/"
            "oracle_queue_dynamic_pareto_<epoch>.jsonl "
            "is used."
        ),
    )

    parser.add_argument(
        "--diagnostics",
        type=Path,
        default=None,
        help=(
            "JSON diagnostics output. If omitted, "
            "data/pareto/pareto_selection_<epoch>.json "
            "is used."
        ),
    )

    parser.add_argument(
        "--budget-fraction",
        type=float,
        default=DEFAULT_BUDGET_FRACTION,
    )

    parser.add_argument(
        "--cv-folds",
        type=int,
        default=DEFAULT_CV_FOLDS,
    )

    parser.add_argument(
        "--trees",
        type=int,
        default=DEFAULT_N_TREES,
    )

    parser.add_argument(
        "--predict-chunk-size",
        type=int,
        default=DEFAULT_PREDICT_CHUNK_SIZE,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing non-empty output queue.",
    )

    parser.add_argument(
        "--diagnostic-only",
        action="store_true",
        help=(
            "Cross-validate the response surrogate, write "
            "diagnostics and stop before queue construction."
        ),
    )

    return parser.parse_args()


# ============================================================
# Reproducibility
# ============================================================

def seed_everything(
    seed: int,
) -> None:

    random.seed(
        seed
    )

    np.random.seed(
        seed
    )


# ============================================================
# Generic helpers
# ============================================================

def safe_float(
    value,
) -> float:

    try:

        value = float(
            value
        )

    except (
        TypeError,
        ValueError,
    ):

        return np.nan

    if not np.isfinite(
        value
    ):

        return np.nan

    return value


def query_id_from_fen(
    fen: str,
) -> str:

    return uuid.uuid5(
        uuid.NAMESPACE_DNS,
        fen,
    ).hex


# ============================================================
# JSON loading
# ============================================================

def load_json_records(
    path: Path,
) -> list[dict]:

    if not path.exists():

        raise FileNotFoundError(
            f"File not found:\n{path}"
        )

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:

        payload = json.load(
            file
        )

    if isinstance(
        payload,
        list,
    ):

        return payload

    if isinstance(
        payload,
        dict,
    ):

        for key in (
            "data",
            "records",
            "positions",
            "samples",
            "stats",
            "uncertainty_stats",
        ):

            value = payload.get(
                key
            )

            if isinstance(
                value,
                list,
            ):

                return value

    raise ValueError(
        f"Unsupported JSON structure:\n{path}"
    )


def load_jsonl(
    path: Path,
) -> list[dict]:

    if not path.exists():

        raise FileNotFoundError(
            f"File not found:\n{path}"
        )

    rows = []

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:

        for line_number, line in enumerate(
            file,
            start=1,
        ):

            line = line.strip()

            if not line:
                continue

            try:

                row = json.loads(
                    line
                )

            except json.JSONDecodeError as exc:

                raise ValueError(
                    f"Invalid JSONL at line "
                    f"{line_number} in:\n{path}"
                ) from exc

            if not isinstance(
                row,
                dict,
            ):

                raise ValueError(
                    f"Expected JSON object at line "
                    f"{line_number} in:\n{path}"
                )

            rows.append(
                row
            )

    return rows


# ============================================================
# Probe response dataset
# ============================================================

def load_probe_dataset(
    path: Path,
    *,
    learner_epoch: int,
) -> list[dict]:
    """
    Load the dynamic local-response calibration dataset.

    HU is always recomputed as H * U.
    """

    rows = load_jsonl(
        path
    )

    cleaned = []

    for index, row in enumerate(
        rows
    ):

        for required in (
            "query_id",
            "fen",
            "H",
            "U",
            "delta_kl",
            "delta_v",
        ):

            if required not in row:

                raise ValueError(
                    f"Probe response {index} is missing "
                    f"'{required}'."
                )

        H = safe_float(
            row.get(
                "H"
            )
        )

        U = safe_float(
            row.get(
                "U"
            )
        )

        delta_kl = safe_float(
            row.get(
                "delta_kl"
            )
        )

        delta_v = safe_float(
            row.get(
                "delta_v"
            )
        )

        if (
            not np.isfinite(
                H
            )
            or not np.isfinite(
                U
            )
            or not np.isfinite(
                delta_kl
            )
            or not np.isfinite(
                delta_v
            )
        ):

            raise ValueError(
                f"Non-finite probe response at index {index}."
            )

        if U < 0.0:

            raise ValueError(
                f"Negative U at probe index {index}: {U}"
            )

        if (
            delta_kl < 0.0
            or delta_v < 0.0
        ):

            raise ValueError(
                "Pareto targets must be response magnitudes. "
                f"Probe index {index}: "
                f"delta_kl={delta_kl}, delta_v={delta_v}"
            )

        fen = row.get(
            "fen"
        )

        if (
            not isinstance(
                fen,
                str,
            )
            or not fen
        ):

            raise ValueError(
                f"Invalid FEN at probe index {index}."
            )

        chess.variant.AtomicBoard(
            fen
        )

        row_epoch = row.get(
            "learner_epoch"
        )

        if (
            row_epoch is not None
            and int(
                row_epoch
            ) != learner_epoch
        ):

            raise ValueError(
                "Probe-response epoch mismatch: "
                f"row {index} has learner_epoch={row_epoch}, "
                f"expected {learner_epoch}."
            )

        normalized = dict(
            row
        )

        normalized[
            "H"
        ] = H

        normalized[
            "U"
        ] = U

        normalized[
            "HU"
        ] = (
            H
            * U
        )

        normalized[
            "delta_kl"
        ] = delta_kl

        normalized[
            "delta_v"
        ] = delta_v

        cleaned.append(
            normalized
        )

    if len(
        cleaned
    ) < 20:

        raise RuntimeError(
            "Too few Pareto probe responses: "
            f"{len(cleaned)}."
        )

    return cleaned


# ============================================================
# Feature matrix
# ============================================================

def make_feature_matrix(
    rows: list[dict],
) -> np.ndarray:

    return np.asarray(
        [
            [
                float(
                    row[
                        "H"
                    ]
                ),
                float(
                    row[
                        "U"
                    ]
                ),
                float(
                    row[
                        "H"
                    ]
                )
                * float(
                    row[
                        "U"
                    ]
                ),
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )


# ============================================================
# Surrogate
# ============================================================

def create_surrogate(
    *,
    n_trees: int,
    seed: int,
) -> ExtraTreesRegressor:

    return ExtraTreesRegressor(
        n_estimators=n_trees,
        random_state=seed,
        n_jobs=-1,
        min_samples_leaf=2,
        max_features=1.0,
    )


# ============================================================
# Metrics
# ============================================================

def safe_spearman(
    y_true,
    y_pred,
) -> float:

    y_true = np.asarray(
        y_true,
        dtype=np.float64,
    )

    y_pred = np.asarray(
        y_pred,
        dtype=np.float64,
    )

    mask = (
        np.isfinite(
            y_true
        )
        &
        np.isfinite(
            y_pred
        )
    )

    y_true = y_true[
        mask
    ]

    y_pred = y_pred[
        mask
    ]

    if len(
        y_true
    ) < 3:

        return np.nan

    if (
        np.std(
            y_true
        ) < 1e-12
        or np.std(
            y_pred
        ) < 1e-12
    ):

        return np.nan

    rho = spearmanr(
        y_true,
        y_pred,
    ).statistic

    if not np.isfinite(
        rho
    ):

        return np.nan

    return float(
        rho
    )


def target_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> dict:

    return {
        "r2":
            float(
                r2_score(
                    y_true,
                    y_pred,
                )
            ),

        "mae":
            float(
                mean_absolute_error(
                    y_true,
                    y_pred,
                )
            ),

        "spearman":
            safe_spearman(
                y_true,
                y_pred,
            ),
    }


# ============================================================
# Surrogate cross-validation
# ============================================================

def cross_validate_surrogate(
    rows: list[dict],
    *,
    cv_folds: int,
    n_trees: int,
    seed: int,
) -> tuple[
    dict,
    np.ndarray,
]:

    X = make_feature_matrix(
        rows
    )

    delta_kl = np.asarray(
        [
            row[
                "delta_kl"
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )

    delta_v = np.asarray(
        [
            row[
                "delta_v"
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )

    if cv_folds > len(
        rows
    ):

        raise ValueError(
            "--cv-folds cannot exceed the number "
            "of probe responses."
        )

    Y_log = np.column_stack(
        [
            np.log1p(
                delta_kl
            ),
            np.log1p(
                delta_v
            ),
        ]
    )

    cv = KFold(
        n_splits=cv_folds,
        shuffle=True,
        random_state=seed,
    )

    predicted_log = cross_val_predict(
        create_surrogate(
            n_trees=n_trees,
            seed=seed,
        ),
        X,
        Y_log,
        cv=cv,
        n_jobs=1,
    )

    predicted = np.maximum(
        np.expm1(
            predicted_log
        ),
        0.0,
    )

    metrics = {
        "delta_kl":
            target_metrics(
                delta_kl,
                predicted[
                    :,
                    0
                ],
            ),

        "delta_v":
            target_metrics(
                delta_v,
                predicted[
                    :,
                    1
                ],
            ),
    }

    return (
        metrics,
        predicted,
    )


# ============================================================
# Final surrogate
# ============================================================

def fit_final_surrogate(
    rows: list[dict],
    *,
    n_trees: int,
    seed: int,
) -> ExtraTreesRegressor:

    X = make_feature_matrix(
        rows
    )

    Y = np.asarray(
        [
            [
                math.log1p(
                    float(
                        row[
                            "delta_kl"
                        ]
                    )
                ),
                math.log1p(
                    float(
                        row[
                            "delta_v"
                        ]
                    )
                ),
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )

    model = create_surrogate(
        n_trees=n_trees,
        seed=seed,
    )

    model.fit(
        X,
        Y,
    )

    return model


# ============================================================
# Calibration-probe leakage exclusion
# ============================================================

def load_probe_query_ids(
    path: Path,
) -> set[str]:
    """
    Derive canonical query IDs from FEN whenever possible.

    Stored IDs are not relied upon for leakage prevention.
    """

    rows = load_jsonl(
        path
    )

    query_ids = set()

    for row in rows:

        fen = row.get(
            "fen"
        )

        if (
            isinstance(
                fen,
                str,
            )
            and fen
        ):

            query_ids.add(
                query_id_from_fen(
                    fen
                )
            )

            continue

        stored_id = row.get(
            "query_id"
        )

        if stored_id:

            query_ids.add(
                str(
                    stored_id
                )
            )

    return query_ids


# ============================================================
# Candidate eligibility
# ============================================================

def is_eligible_position(
    fen: str,
) -> bool:

    try:

        board = chess.variant.AtomicBoard(
            fen
        )

    except Exception:

        return False

    return (
        board.legal_moves.count()
        > 1
    )


# ============================================================
# Candidate pool
# ============================================================

def build_candidate_pool(
    records: list[dict],
    excluded_ids: set[str],
) -> tuple[
    list[dict],
    dict,
]:
    """
    Construct unique, legal, non-probe candidate FENs.

    HU is recomputed as H * U.
    """

    print()
    print(
        "Filtering candidate pool...",
        flush=True,
    )

    candidates = []

    seen_ids = set()

    counters = {
        "excluded_probe":
            0,

        "duplicate":
            0,

        "ineligible":
            0,

        "invalid":
            0,
    }

    matched_probe_ids = set()

    for index, record in enumerate(
        records
    ):

        if (
            index > 0
            and index % 100000 == 0
        ):

            print(
                f"  checked "
                f"{index:,} / {len(records):,}",
                flush=True,
            )

        if not isinstance(
            record,
            dict,
        ):

            counters[
                "invalid"
            ] += 1

            continue

        fen = record.get(
            "fen"
        )

        H = safe_float(
            record.get(
                "H"
            )
        )

        U = safe_float(
            record.get(
                "U"
            )
        )

        if (
            not isinstance(
                fen,
                str,
            )
            or not fen
            or not np.isfinite(
                H
            )
            or not np.isfinite(
                U
            )
            or U < 0.0
        ):

            counters[
                "invalid"
            ] += 1

            continue

        query_id = query_id_from_fen(
            fen
        )

        # ----------------------------------------------------
        # Calibration leakage
        # ----------------------------------------------------

        if query_id in excluded_ids:

            counters[
                "excluded_probe"
            ] += 1

            matched_probe_ids.add(
                query_id
            )

            continue

        # ----------------------------------------------------
        # Duplicate FEN
        # ----------------------------------------------------

        if query_id in seen_ids:

            counters[
                "duplicate"
            ] += 1

            continue

        seen_ids.add(
            query_id
        )

        # ----------------------------------------------------
        # Oracle eligibility
        # ----------------------------------------------------

        if not is_eligible_position(
            fen
        ):

            counters[
                "ineligible"
            ] += 1

            continue

        candidates.append(
            {
                "source_index":
                    index,

                "query_id":
                    query_id,

                "fen":
                    fen,

                "H":
                    H,

                "U":
                    U,

                "HU":
                    H
                    * U,

                "model":
                    record.get(
                        "model"
                    ),

                "epoch":
                    record.get(
                        "epoch",
                        -1,
                    ),

                "game_id":
                    record.get(
                        "game_id",
                        -1,
                    ),

                "ply":
                    record.get(
                        "ply",
                        -1,
                    ),
            }
        )

    diagnostics = {
        **counters,

        "matched_probe_ids":
            len(
                matched_probe_ids
            ),

        "total_probe_ids":
            len(
                excluded_ids
            ),

        "eligible_candidates":
            len(
                candidates
            ),
    }

    return (
        candidates,
        diagnostics,
    )


# ============================================================
# Chunked prediction
# ============================================================

def predict_candidates(
    model: ExtraTreesRegressor,
    candidates: list[dict],
    *,
    chunk_size: int,
) -> tuple[
    np.ndarray,
    np.ndarray,
]:

    n = len(
        candidates
    )

    predicted_kl = np.empty(
        n,
        dtype=np.float64,
    )

    predicted_v = np.empty(
        n,
        dtype=np.float64,
    )

    print()
    print(
        "Projecting candidate pool into response space...",
        flush=True,
    )

    for start in range(
        0,
        n,
        chunk_size,
    ):

        end = min(
            start
            + chunk_size,
            n,
        )

        X = make_feature_matrix(
            candidates[
                start:end
            ]
        )

        prediction_log = model.predict(
            X
        )

        prediction = np.maximum(
            np.expm1(
                prediction_log
            ),
            0.0,
        )

        predicted_kl[
            start:end
        ] = prediction[
            :,
            0
        ]

        predicted_v[
            start:end
        ] = prediction[
            :,
            1
        ]

        print(
            f"  predicted {end:,} / {n:,}",
            flush=True,
        )

    return (
        predicted_kl,
        predicted_v,
    )


# ============================================================
# Fenwick tree
# ============================================================

class FenwickMax:

    def __init__(
        self,
        size: int,
    ) -> None:

        self.size = size

        self.tree = np.zeros(
            size
            + 1,
            dtype=np.int32,
        )

    def query(
        self,
        index: int,
    ) -> int:

        result = 0

        while index > 0:

            result = max(
                result,
                int(
                    self.tree[
                        index
                    ]
                ),
            )

            index -= (
                index
                & -index
            )

        return result

    def update(
        self,
        index: int,
        value: int,
    ) -> None:

        while index <= self.size:

            if value > self.tree[
                index
            ]:

                self.tree[
                    index
                ] = value

            index += (
                index
                & -index
            )


# ============================================================
# Exact 2D Pareto ranks
# ============================================================

def pareto_ranks_2d(
    objective_1,
    objective_2,
) -> np.ndarray:
    """
    Exact non-dominated layer numbers for two objectives.

    Both objectives are maximized.

    Rank 1:
        non-dominated points

    Rank 2:
        non-dominated after removal of rank 1

    etc.

    Exact duplicate objective pairs receive the same rank.
    """

    x = np.asarray(
        objective_1,
        dtype=np.float64,
    )

    y = np.asarray(
        objective_2,
        dtype=np.float64,
    )

    if len(
        x
    ) != len(
        y
    ):

        raise ValueError(
            "Objective arrays have different lengths."
        )

    if len(
        x
    ) == 0:

        raise ValueError(
            "No objective values."
        )

    if not (
        np.all(
            np.isfinite(
                x
            )
        )
        and np.all(
            np.isfinite(
                y
            )
        )
    ):

        raise ValueError(
            "Pareto objectives contain non-finite values."
        )

    print()
    print(
        "Computing exact 2D Pareto layers...",
        flush=True,
    )

    unique_y = np.unique(
        y
    )

    # Largest y -> Fenwick index 1.
    y_index = (
        len(
            unique_y
        )
        - np.searchsorted(
            unique_y,
            y,
            side="left",
        )
    )

    # Primary key: x descending.
    # Secondary key: y descending.
    order = np.lexsort(
        (
            -y,
            -x,
        )
    )

    ranks = np.empty(
        len(
            x
        ),
        dtype=np.int32,
    )

    fenwick = FenwickMax(
        len(
            unique_y
        )
    )

    position = 0

    while position < len(
        x
    ):

        index = order[
            position
        ]

        current_x = x[
            index
        ]

        current_y = y[
            index
        ]

        end = (
            position
            + 1
        )

        # Exact duplicate objective pairs must not dominate
        # one another.
        while end < len(
            x
        ):

            other = order[
                end
            ]

            if (
                x[
                    other
                ] != current_x
                or y[
                    other
                ] != current_y
            ):

                break

            end += 1

        yi = int(
            y_index[
                index
            ]
        )

        rank = (
            fenwick.query(
                yi
            )
            + 1
        )

        group = order[
            position:end
        ]

        ranks[
            group
        ] = rank

        fenwick.update(
            yi,
            rank,
        )

        position = end

    return ranks


# ============================================================
# Crowding distance
# ============================================================

def crowding_distance(
    indices,
    objective_1: np.ndarray,
    objective_2: np.ndarray,
) -> np.ndarray:

    indices = np.asarray(
        indices,
        dtype=np.int64,
    )

    n = len(
        indices
    )

    if n == 0:

        return np.empty(
            0,
            dtype=np.float64,
        )

    if n <= 2:

        return np.full(
            n,
            np.inf,
            dtype=np.float64,
        )

    distance = np.zeros(
        n,
        dtype=np.float64,
    )

    for values in (
        objective_1[
            indices
        ],
        objective_2[
            indices
        ],
    ):

        order = np.argsort(
            values,
            kind="stable",
        )

        minimum = values[
            order[
                0
            ]
        ]

        maximum = values[
            order[
                -1
            ]
        ]

        distance[
            order[
                0
            ]
        ] = np.inf

        distance[
            order[
                -1
            ]
        ] = np.inf

        span = (
            maximum
            - minimum
        )

        if span <= 0.0:

            continue

        interior = order[
            1:-1
        ]

        distance[
            interior
        ] += (
            values[
                order[
                    2:
                ]
            ]
            - values[
                order[
                    :-2
                ]
            ]
        ) / span

    return distance


# ============================================================
# Budgeted Pareto selection
# ============================================================

def select_budget(
    *,
    pareto_ranks: np.ndarray,
    predicted_kl: np.ndarray,
    predicted_v: np.ndarray,
    budget: int,
) -> np.ndarray:

    if budget <= 0:

        raise ValueError(
            "Budget must be positive."
        )

    if budget > len(
        pareto_ranks
    ):

        raise ValueError(
            "Budget exceeds candidate count."
        )

    selected = []

    max_rank = int(
        np.max(
            pareto_ranks
        )
    )

    print()
    print(
        "Pareto front occupancy:",
        flush=True,
    )

    for rank in range(
        1,
        max_rank
        + 1,
    ):

        front = np.flatnonzero(
            pareto_ranks
            == rank
        )

        if len(
            front
        ) == 0:

            continue

        remaining = (
            budget
            - len(
                selected
            )
        )

        print(
            f"  Front {rank:3d}: "
            f"{len(front):,}",
            flush=True,
        )

        if remaining <= 0:

            break

        if len(
            front
        ) <= remaining:

            selected.extend(
                front.tolist()
            )

            continue

        # ----------------------------------------------------
        # Only the final partially selected front needs
        # crowding-distance ranking.
        # ----------------------------------------------------

        distances = crowding_distance(
            front,
            predicted_kl,
            predicted_v,
        )

        local_order = sorted(
            range(
                len(
                    front
                )
            ),
            key=lambda local_index: (
                -distances[
                    local_index
                ],
                -predicted_kl[
                    front[
                        local_index
                    ]
                ],
                -predicted_v[
                    front[
                        local_index
                    ]
                ],
                int(
                    front[
                        local_index
                    ]
                ),
            ),
        )

        selected.extend(
            [
                int(
                    front[
                        local_index
                    ]
                )
                for local_index
                in local_order[
                    :remaining
                ]
            ]
        )

        break

    if len(
        selected
    ) != budget:

        raise RuntimeError(
            f"Expected {budget} selected positions, "
            f"obtained {len(selected)}."
        )

    return np.asarray(
        selected,
        dtype=np.int64,
    )


# ============================================================
# Queue writer
# ============================================================

def write_hmi_queue(
    *,
    candidates: list[dict],
    selected_indices: np.ndarray,
    predicted_kl: np.ndarray,
    predicted_v: np.ndarray,
    pareto_ranks: np.ndarray,
    output_path: Path,
    learner_epoch: int,
    force: bool,
) -> None:

    if (
        output_path.exists()
        and output_path.stat().st_size > 0
        and not force
    ):

        raise FileExistsError(
            f"Output queue already exists:\n"
            f"{output_path}\n\n"
            "Use --force to overwrite it."
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    created_at = datetime.now(
        timezone.utc
    ).isoformat()

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:

        for selected_index in selected_indices:

            index = int(
                selected_index
            )

            candidate = candidates[
                index
            ]

            item = {
                "query_id":
                    candidate[
                        "query_id"
                    ],

                "fen":
                    candidate[
                        "fen"
                    ],

                "H":
                    float(
                        candidate[
                            "H"
                        ]
                    ),

                "U":
                    float(
                        candidate[
                            "U"
                        ]
                    ),

                "HU":
                    float(
                        candidate[
                            "HU"
                        ]
                    ),

                # --------------------------------------------
                # No scalar AL score is involved.
                # --------------------------------------------

                "score":
                    None,

                "I_norm":
                    None,

                "threshold":
                    None,

                # --------------------------------------------
                # Pareto provenance
                # --------------------------------------------

                "acquisition":
                    "dynamic_pareto_response",

                "predicted_delta_kl":
                    float(
                        predicted_kl[
                            index
                        ]
                    ),

                "predicted_delta_v":
                    float(
                        predicted_v[
                            index
                        ]
                    ),

                "pareto_rank":
                    int(
                        pareto_ranks[
                            index
                        ]
                    ),

                "learner_epoch":
                    learner_epoch,

                # --------------------------------------------
                # Source metadata
                # --------------------------------------------

                "model":
                    candidate.get(
                        "model",
                        "dynamic_pareto",
                    ),

                "epoch":
                    candidate.get(
                        "epoch",
                        -1,
                    ),

                "game_id":
                    candidate.get(
                        "game_id",
                        -1,
                    ),

                "ply":
                    candidate.get(
                        "ply",
                        -1,
                    ),

                "created_at":
                    created_at,

                # --------------------------------------------
                # Canonical Oracle lifecycle
                # --------------------------------------------

                "status":
                    "pending",

                "oracle_move":
                    None,

                "oracle_confidence":
                    None,

                "oracle_situation":
                    None,

                "reward":
                    None,

                "answered_at":
                    None,
            }

            file.write(
                json.dumps(
                    item,
                    ensure_ascii=False,
                )
                + "\n"
            )


# ============================================================
# Quantile summary
# ============================================================

def quantile_summary(
    values,
) -> dict:

    values = np.asarray(
        values,
        dtype=np.float64,
    )

    return {
        "min":
            float(
                np.min(
                    values
                )
            ),

        "p10":
            float(
                np.percentile(
                    values,
                    10,
                )
            ),

        "p25":
            float(
                np.percentile(
                    values,
                    25,
                )
            ),

        "median":
            float(
                np.median(
                    values
                )
            ),

        "p75":
            float(
                np.percentile(
                    values,
                    75,
                )
            ),

        "p90":
            float(
                np.percentile(
                    values,
                    90,
                )
            ),

        "max":
            float(
                np.max(
                    values
                )
            ),
    }


def print_quantiles(
    name: str,
    values,
) -> None:

    summary = quantile_summary(
        values
    )

    print()
    print(
        name
    )

    for key in (
        "min",
        "p10",
        "p25",
        "median",
        "p75",
        "p90",
        "max",
    ):

        print(
            f"  {key:>6s}: "
            f"{summary[key]:.6e}"
        )


# ============================================================
# Probe correlations
# ============================================================

def probe_correlations(
    rows: list[dict],
) -> dict:

    delta_kl = np.asarray(
        [
            row[
                "delta_kl"
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )

    delta_v = np.asarray(
        [
            row[
                "delta_v"
            ]
            for row
            in rows
        ],
        dtype=np.float64,
    )

    output = {}

    for feature_name in FEATURE_NAMES:

        if feature_name == "HU":

            values = np.asarray(
                [
                    row[
                        "H"
                    ]
                    * row[
                        "U"
                    ]
                    for row
                    in rows
                ],
                dtype=np.float64,
            )

        else:

            values = np.asarray(
                [
                    row[
                        feature_name
                    ]
                    for row
                    in rows
                ],
                dtype=np.float64,
            )

        output[
            feature_name
        ] = {
            "delta_kl_spearman":
                safe_spearman(
                    values,
                    delta_kl,
                ),

            "delta_v_spearman":
                safe_spearman(
                    values,
                    delta_v,
                ),
        }

    return output


# ============================================================
# Diagnostics writer
# ============================================================

def write_diagnostics(
    *,
    path: Path,
    learner_epoch: int,
    seed: int,
    budget_fraction: float,
    raw_pool_size: int | None,
    budget: int | None,
    probe_count: int,
    cv_metrics: dict,
    correlations: dict,
    candidate_diagnostics: dict | None,
    selected_diagnostics: dict | None,
) -> None:

    payload = {
        "learner_epoch":
            learner_epoch,

        "seed":
            seed,

        "budget_fraction":
            budget_fraction,

        "raw_pool_size":
            raw_pool_size,

        "budget":
            budget,

        "probe_count":
            probe_count,

        "features":
            list(
                FEATURE_NAMES
            ),

        "targets": [
            "delta_kl",
            "delta_v",
        ],

        "target_semantics": {
            "delta_kl":
                "KL(policy_before || policy_after)",

            "delta_v":
                "abs(value_after - value_before)",
        },

        "cv_metrics":
            cv_metrics,

        "probe_correlations":
            correlations,

        "candidate_filtering":
            candidate_diagnostics,

        "selected":
            selected_diagnostics,
    }

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            payload,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# Main
# ============================================================

def main() -> None:

    args = parse_args()

    if args.learner_epoch < 0:

        raise ValueError(
            "--learner-epoch must be non-negative."
        )

    if not (
        0.0
        < args.budget_fraction
        <= 1.0
    ):

        raise ValueError(
            "--budget-fraction must be in (0, 1]."
        )

    if args.cv_folds < 2:

        raise ValueError(
            "--cv-folds must be >= 2."
        )

    if args.trees <= 0:

        raise ValueError(
            "--trees must be positive."
        )

    if args.predict_chunk_size <= 0:

        raise ValueError(
            "--predict-chunk-size must be positive."
        )

    seed_everything(
        args.seed
    )

    pool_path = args.pool

    if pool_path is None:

        pool_path = (
            DEFAULT_SELFPLAY_DIR
            / (
                "uncertainty_stats_pareto_oracle_"
                f"{args.learner_epoch}.json"
            )
        )

    output_path = args.output

    if output_path is None:

        output_path = (
            DEFAULT_QUEUE_DIR
            / (
                "oracle_queue_dynamic_pareto_"
                f"{args.learner_epoch}.jsonl"
            )
        )

    diagnostic_path = args.diagnostics

    if diagnostic_path is None:

        diagnostic_path = (
            DEFAULT_DIAGNOSTIC_DIR
            / (
                "pareto_selection_"
                f"{args.learner_epoch}.json"
            )
        )

    # ========================================================
    # Header
    # ========================================================

    print()
    print("=" * 72)
    print("ALBERTA - DYNAMIC PARETO ACQUISITION")
    print("=" * 72)

    print(
        f"Learner epoch:   {args.learner_epoch}"
    )

    print(
        f"Probe responses: {args.probe_responses}"
    )

    print(
        f"Probe queue:     {args.probe_queue}"
    )

    print(
        f"Candidate pool:  {pool_path}"
    )

    print(
        f"Output queue:    {output_path}"
    )

    print(
        f"Budget fraction: "
        f"{args.budget_fraction:.6f} "
        f"({args.budget_fraction * 100:.4f}%)"
    )

    print(
        f"Features:        {FEATURE_NAMES}"
    )

    print(
        f"Trees:           {args.trees}"
    )

    print(
        f"CV folds:        {args.cv_folds}"
    )

    print(
        f"Seed:            {args.seed}"
    )

    # ========================================================
    # Probe responses
    # ========================================================

    probes = load_probe_dataset(
        args.probe_responses,
        learner_epoch=args.learner_epoch,
    )

    print()
    print(
        f"Probe responses loaded: {len(probes):,}"
    )

    correlations = probe_correlations(
        probes
    )

    print()
    print("=" * 72)
    print("PROBE RESPONSE CORRELATIONS")
    print("=" * 72)

    for (
        feature_name,
        values,
    ) in correlations.items():

        print(
            f"{feature_name:<4s} "
            f"| rho(KL)="
            f"{values['delta_kl_spearman']:+.4f} "
            f"| rho(|dV|)="
            f"{values['delta_v_spearman']:+.4f}"
        )

    # ========================================================
    # Cross-validation
    # ========================================================

    (
        cv_metrics,
        _,
    ) = cross_validate_surrogate(
        probes,
        cv_folds=args.cv_folds,
        n_trees=args.trees,
        seed=args.seed,
    )

    print()
    print("=" * 72)
    print("SURROGATE CROSS-VALIDATION")
    print("=" * 72)

    for target_name in (
        "delta_kl",
        "delta_v",
    ):

        metrics = cv_metrics[
            target_name
        ]

        print(
            f"{target_name:<10s} "
            f"R2={metrics['r2']:+.4f} | "
            f"MAE={metrics['mae']:.6e} | "
            f"Spearman={metrics['spearman']:+.4f}"
        )

    if args.diagnostic_only:

        write_diagnostics(
            path=diagnostic_path,
            learner_epoch=args.learner_epoch,
            seed=args.seed,
            budget_fraction=args.budget_fraction,
            raw_pool_size=None,
            budget=None,
            probe_count=len(
                probes
            ),
            cv_metrics=cv_metrics,
            correlations=correlations,
            candidate_diagnostics=None,
            selected_diagnostics=None,
        )

        print()
        print(
            "Diagnostic-only mode: no queue generated."
        )

        print(
            f"Diagnostics: {diagnostic_path}"
        )

        return

    # ========================================================
    # Fit surrogate
    # ========================================================

    surrogate = fit_final_surrogate(
        probes,
        n_trees=args.trees,
        seed=args.seed,
    )

    # ========================================================
    # Pool / historical budget semantics
    # ========================================================

    records = load_json_records(
        pool_path
    )

    raw_pool_size = len(
        records
    )

    budget = max(
        1,
        int(
            round(
                raw_pool_size
                * args.budget_fraction
            )
        ),
    )

    print()
    print("=" * 72)
    print("CANDIDATE POOL")
    print("=" * 72)

    print(
        f"Raw pool size: {raw_pool_size:,}"
    )

    print(
        f"Budget:        {budget:,}"
    )

    # ========================================================
    # Exclude fixed calibration probes
    # ========================================================

    excluded_ids = load_probe_query_ids(
        args.probe_queue
    )

    (
        candidates,
        candidate_diagnostics,
    ) = build_candidate_pool(
        records,
        excluded_ids,
    )

    print(
        f"Eligible unique candidates: "
        f"{len(candidates):,}"
    )

    print(
        f"Calibration positions removed: "
        f"{candidate_diagnostics['excluded_probe']:,}"
    )

    print(
        f"Duplicate FENs removed: "
        f"{candidate_diagnostics['duplicate']:,}"
    )

    print(
        f"Ineligible positions removed: "
        f"{candidate_diagnostics['ineligible']:,}"
    )

    print(
        f"Invalid records removed: "
        f"{candidate_diagnostics['invalid']:,}"
    )

    if len(
        candidates
    ) < budget:

        raise RuntimeError(
            "Eligible candidate pool is smaller "
            "than the annotation budget."
        )

    # ========================================================
    # Predict local responses
    # ========================================================

    (
        predicted_kl,
        predicted_v,
    ) = predict_candidates(
        surrogate,
        candidates,
        chunk_size=args.predict_chunk_size,
    )

    print_quantiles(
        "Predicted Delta KL - eligible pool",
        predicted_kl,
    )

    print_quantiles(
        "Predicted |Delta V| - eligible pool",
        predicted_v,
    )

    # ========================================================
    # Pareto sorting
    # ========================================================

    pareto_ranks = pareto_ranks_2d(
        predicted_kl,
        predicted_v,
    )

    selected = select_budget(
        pareto_ranks=pareto_ranks,
        predicted_kl=predicted_kl,
        predicted_v=predicted_v,
        budget=budget,
    )

    # ========================================================
    # Selected distributions
    # ========================================================

    selected_kl = predicted_kl[
        selected
    ]

    selected_v = predicted_v[
        selected
    ]

    selected_ranks = pareto_ranks[
        selected
    ]

    selected_H = np.asarray(
        [
            candidates[
                int(
                    index
                )
            ][
                "H"
            ]
            for index
            in selected
        ],
        dtype=np.float64,
    )

    selected_U = np.asarray(
        [
            candidates[
                int(
                    index
                )
            ][
                "U"
            ]
            for index
            in selected
        ],
        dtype=np.float64,
    )

    selected_HU = (
        selected_H
        * selected_U
    )

    print()
    print("=" * 72)
    print("FINAL PARETO SELECTION")
    print("=" * 72)

    print(
        f"Selected:          {len(selected):,}"
    )

    print(
        f"Pareto rank range: "
        f"{selected_ranks.min()} -> "
        f"{selected_ranks.max()}"
    )

    print_quantiles(
        "Selected H",
        selected_H,
    )

    print_quantiles(
        "Selected U",
        selected_U,
    )

    print_quantiles(
        "Selected HU",
        selected_HU,
    )

    print_quantiles(
        "Selected predicted Delta KL",
        selected_kl,
    )

    print_quantiles(
        "Selected predicted |Delta V|",
        selected_v,
    )

    pool_response_rho = safe_spearman(
        predicted_kl,
        predicted_v,
    )

    selected_response_rho = safe_spearman(
        selected_kl,
        selected_v,
    )

    print()
    print(
        "Predicted response correlation:"
    )

    print(
        f"  eligible pool : "
        f"{pool_response_rho:+.4f}"
    )

    print(
        f"  selected set  : "
        f"{selected_response_rho:+.4f}"
    )

    # ========================================================
    # Queue
    # ========================================================

    write_hmi_queue(
        candidates=candidates,
        selected_indices=selected,
        predicted_kl=predicted_kl,
        predicted_v=predicted_v,
        pareto_ranks=pareto_ranks,
        output_path=output_path,
        learner_epoch=args.learner_epoch,
        force=args.force,
    )

    # ========================================================
    # Persistent diagnostics
    # ========================================================

    selected_diagnostics = {
        "n_selected":
            len(
                selected
            ),

        "pareto_rank_min":
            int(
                selected_ranks.min()
            ),

        "pareto_rank_max":
            int(
                selected_ranks.max()
            ),

        "pool_response_spearman":
            pool_response_rho,

        "selected_response_spearman":
            selected_response_rho,

        "H":
            quantile_summary(
                selected_H
            ),

        "U":
            quantile_summary(
                selected_U
            ),

        "HU":
            quantile_summary(
                selected_HU
            ),

        "predicted_delta_kl":
            quantile_summary(
                selected_kl
            ),

        "predicted_delta_v":
            quantile_summary(
                selected_v
            ),
    }

    write_diagnostics(
        path=diagnostic_path,
        learner_epoch=args.learner_epoch,
        seed=args.seed,
        budget_fraction=args.budget_fraction,
        raw_pool_size=raw_pool_size,
        budget=budget,
        probe_count=len(
            probes
        ),
        cv_metrics=cv_metrics,
        correlations=correlations,
        candidate_diagnostics=(
            candidate_diagnostics
        ),
        selected_diagnostics=(
            selected_diagnostics
        ),
    )

    # ========================================================
    # Final
    # ========================================================

    print()
    print("=" * 72)
    print("DYNAMIC PARETO QUEUE CREATED")
    print("=" * 72)

    print(
        f"Queue:       {output_path}"
    )

    print(
        f"Diagnostics: {diagnostic_path}"
    )


# ============================================================
# Entry point
# ============================================================

if __name__ == "__main__":

    main()